### ISSUE TITLE
Can this library rotate multiple images?

### ISSUE THREAD

**Issue by matteobruni** [matteobruni/tsparticles#116]
> I was able to draw multiple images.
> But I don't know how to rotate each one.
> Please help me.
> 
> https://codepen.io/freakale/pen/YzXxZEK

Original Project issue https://github.com/VincentGarreau/particles.js/issues/427 by @freakale

---

The original project is abandoned, this feature seems really interesting, I'll have a look on it

**Comment by matteobruni** [comment]
Issue https://github.com/VincentGarreau/particles.js/issues/427 on the original project

**Comment by matteobruni** [comment]
Particles rotation is ready for the next release

**Comment by freakale** [comment]
Thank you very much.

**Comment by matteobruni** [comment]
https://codepen.io/matteobruni/pen/bGdomGq

You can checkout this sample for the options

**Comment by matteobruni** [comment]
Sorry, there was a bug in the 1.9.1, the 1.9.2 is out now and fixes the initial rotation of each particles if set to random o animation.sync false
