### ISSUE TITLE
On hover bubble works as hole to show underlying background

### ISSUE THREAD

**Issue by matteobruni** [matteobruni/tsparticles#117]
> Hello I have tried and tried to work out if this is possible using particle.js
> 
> I want an image as a background and a white layer over this that when you hover over the particle layer the bubbles show image underneath a bit like this.
> 
> https://revolution.themepunch.com/particle-effect-for-wordpress/
> 
> any help would help me keep little hair I have left lol
> 
> Kind regards
> 
> Mike

Original project issue https://github.com/VincentGarreau/particles.js/issues/428 thanks to @Mickperks

---

The original project is abandoned, I'll have a look on it, it seems really cool

**Comment by matteobruni** [comment]
This feature will be released in the next version

**Comment by Mickperks** [comment]
Hello

That sounds excellent

any idea when this would be

Mike

**Comment by matteobruni** [comment]
It's already live

You can checkout the codepen sample here: https://codepen.io/matteobruni/pen/yLNvqxG

**Comment by Mickperks** [comment]
wow excellent work

what did you have to do?

amazing and thank you your the man!

:)

KInd regards

Mike

**Comment by matteobruni** [comment]
It was not so hard, the HTML canvas already has this feature, I activate it when the config needs it.

Hope it works fine, if you need help I'm here

**Comment by Mickperks** [comment]
Hi
I have been using your particle.js json file with smartslider 3

which woks really well i have let them know you have updated this

be great if could get to work in there

kind regards

Mike
