### ISSUE TITLE
Particles emitters

### ISSUE THREAD

**Issue by matteobruni** [matteobruni/tsparticles#140]
New feature about places that emits new particles

**Comment by matteobruni** [comment]
This repo https://github.com/lindelof/particles-bg samples is what I'm talking about

**Comment by mbelic** [comment]
Hello, 

Thank you for the great work on the particle system. 
I was wondering if there are any options to make particles start from one particular part of the screen or point? Now they are all rendered on the whole canvas area and start from there.

Is this issue connected with that - namely emitters?

**Comment by matteobruni** [comment]
Hi @mbelic,

Yes this issue is what you're describing. I hope to start working on them before April ends. I found some bugs and I'm preparing the 1.12.8 version.

You can have a similar effect using the move direction but they are the same particles following a direction, like the `Big Particles` preset on the [demo website](https://particles.matteobruni.it)

**Comment by mbelic** [comment]
Thanks for info. Good luck on next version!

**Comment by matteobruni** [comment]
A little sneak peek

![](https://media.giphy.com/media/fXu92EygLvNpUhZTAo/giphy.gif)

For starting today it's something, if you want to test it I can release an alpha version

**Comment by matteobruni** [comment]
@mbelic I've released the 1.13.0-alpha.0 for testing emitters, if you want you can test it
