### ISSUE TITLE
Unify color management

### ISSUE THREAD

**Issue by matteobruni** [matteobruni/tsparticles#143]
The color properties in the options are not aligned, they should instead use the same properties and values possibilities.

Thanks to @calebfergie it's interesting to have a more customizable opacity. This could be integrated in the color options instead of being separated.

The random color/opacity options should be a boolean option and not a "random" string. LineLinked have a valid "mid" value that creates a gradient from p1 to p2 based on radius difference, this should be a boolean instead of a string "mid"

**Comment by calebfergie** [comment]
@matteobruni thanks for taking note! I'm an amateur, brutishly making "good enough" 

This is what i made with it so far: https://blockapps.net/experiments/strato-network-visualization/

Totally agree integration into the color options would be even better.

**Comment by mobbjelly** [comment]
Do the particles and link lines support user-defined gradient color?

**Comment by matteobruni** [comment]
No, they don't. Actually uses only rgb/hsl objects or hex strings. Adding gradients probably would need some reworks.A feature request will be opened, or you can open it yourself
