### ISSUE TITLE
Particles become distorted. Various CODE.

### ISSUE THREAD

**Issue by matteobruni** [matteobruni/tsparticles#175]
Issue https://github.com/VincentGarreau/particles.js/issues/433 from the original project

> Good morning! Previously I would like to thank everyone!
> 
> My site: http://www.wizardingescaperooms.com/
> 
> I am going crazy looking for a solution. If I add the particles to the section, in the long run, they become distorted.
> 
> I have added the following code, and they look perfectly, but they do not cover the total of the page, I have touched several values, but it always lengthens and blurs the particles.
> 
> **PARTICLE CODE**
> 
> `particlesJS('fondo_particulas1', { "particles": { "number": { "value": 600, "density": { "enable": true, "value_area": 800 } }, "color": { "value": "#ffffff" }, "shape": { "type": "circle", "stroke": { "width": 0, "color": "#000000" }, "polygon": { "nb_sides": 8 }, "image": { "src": "img/github.svg", "width": 100, "height": 100 } }, "opacity": { "value": 1, "random": false, "anim": { "enable": true, "speed": 2.7610625218245732, "opacity_min": 0, "sync": false } }, "size": { "value": 1, "random": true, "anim": { "enable": true, "speed": 0, "size_min": 97.44926547616141, "sync": true } }, "line_linked": { "enable": false, "distance": 0, "color": "#ffffff", "opacity": 0.4, "width": 1 }, "move": { "enable": true, "speed": 0, "direction": "none", "random": true, "straight": false, "out_mode": "bounce", "bounce": false, "attract": { "enable": false, "rotateX": 100, "rotateY": 100 } } }, "interactivity": { "detect_on": "canvas", "events": { "onhover": { "enable": false, "mode": "bubble" }, "onclick": { "enable": false, "mode": "repulse" }, "resize": true }, "modes": { "grab": { "distance": 97.44926547616143, "line_linked": { "opacity": 0.7239044775137166 } }, "bubble": { "distance": 250, "size": 0, "duration": 2, "opacity": 0, "speed": 3 }, "repulse": { "distance": 400, "duration": 0.4 }, "push": { "particles_nb": 4 }, "remove": { "particles_nb": 2 } } }, "retina_detect": true } );`
> 
> **ADDITIONAL CSS CODE**
> 
> `/*Fondo estrellado alto total sin pixelar*/.particles-js-canvas-el { height: 100vmax !important; z-index: 0; } `
> Do you know any solution?
> Thank you!

This issue was reported in the original project by @EdgarGR

This is the config beautified

```json
{
  "particles": {
    "number": {
      "value": 600,
      "density": {
        "enable": true,
        "value_area": 800
      }
    },
    "color": {
      "value": "#ffffff"
    },
    "shape": {
      "type": "circle",
      "stroke": {
        "width": 0,
        "color": "#000000"
      },
      "polygon": {
        "nb_sides": 8
      },
      "image": {
        "src": "img/github.svg",
        "width": 100,
        "height": 100
      }
    },
    "opacity": {
      "value": 1,
      "random": false,
      "anim": {
        "enable": true,
        "speed": 2.7610625218245732,
        "opacity_min": 0,
        "sync": false
      }
    },
    "size": {
      "value": 1,
      "random": true,
      "anim": {
        "enable": true,
        "speed": 0,
        "size_min": 97.44926547616141,
        "sync": true
      }
    },
    "line_linked": {
      "enable": false,
      "distance": 0,
      "color": "#ffffff",
      "opacity": 0.4,
      "width": 1
    },
    "move": {
      "enable": true,
      "speed": 0,
      "direction": "none",
      "random": true,
      "straight": false,
      "out_mode": "bounce",
      "bounce": false,
      "attract": {
        "enable": false,
        "rotateX": 100,
        "rotateY": 100
      }
    }
  },
  "interactivity": {
    "detect_on": "canvas",
    "events": {
      "onhover": {
        "enable": false,
        "mode": "bubble"
      },
      "onclick": {
        "enable": false,
        "mode": "repulse"
      },
      "resize": true
    },
    "modes": {
      "grab": {
        "distance": 97.44926547616143,
        "line_linked": {
          "opacity": 0.7239044775137166
        }
      },
      "bubble": {
        "distance": 250,
        "size": 0,
        "duration": 2,
        "opacity": 0,
        "speed": 3
      },
      "repulse": {
        "distance": 400,
        "duration": 0.4
      },
      "push": {
        "particles_nb": 4
      },
      "remove": {
        "particles_nb": 2
      }
    }
  },
  "retina_detect": true
}
```

The original project is abandoned and you won't find any help, try with this project and if it's affected by the same bug we can find a solution

**Comment by matteobruni** [comment]
@EdgarGR this code pen seems to work fine: https://codepen.io/matteobruni/pen/XWbxQwB

Tell me if it's the solution you were searching

**Comment by EdgarGR** [comment]
Hi Matteo! I need delete the other one? or put in CSS ADITTIONAL CODE?
Thanks for your help!

**Comment by EdgarGR** [comment]
Sorry i'm using (ParticleJS Background). Inside i have the code. But if i put the new one. I can't see anything. 
I see in your link looks well. Can you explain me how i can add to my page. 
Thanks alot!!

**Comment by matteobruni** [comment]
The other issue can stay if you want, here I quoted all text. In the codepen I changed the CSS 

```css
#tsparticles {
  position: absolute;
  width: 100%;
  height: 800vh; // changed here!
  background-color: #010101;
  background-image: url("");
  background-repeat: no-repeat;
  background-size: cover;
  background-position: 50% 50%;
}
```

to simulate a very long container. It seems to work fine, you can try just changing the script reference.

I was checking you CSS and probably it's the issue:

```css
/*Fondo estrellado alto total sin pixelar*/
.particles-js-canvas-el { // change the selector to its parent
  height: 100vmax !important;
  z-index: 0;
}
```

The canvas element style should be left as clean as possible, the canvas is 100% width and height of its container, probably just setting the height to its container solves the issue.

Anyway you can use this project to limit the FPS and improve a little the performance, because the old particles.js pushes the CPU to its limit.

An improvement about performance is under analysis as you can see here #174 because a lot of particles will be a pain in UX.

**Comment by matteobruni** [comment]
> Sorry i'm using (ParticleJS Background). Inside i have the code. But if i put the new one. I can't see anything.
> I see in your link looks well. Can you explain me how i can add to my page.
> Thanks alot!!

Are you using Wordpress? Is this the plugin are you using? https://wordpress.org/plugins/particle-background-wp/#description

I asked them to replace the old particles.js with this new project but no answer yet.

Anyway you can replace the particles.js in the plugin folder with this file https://cdn.jsdelivr.net/npm/tsparticles@1.10.4/dist/tsparticles.min.js

And you can change the line 204 of the plugin.php inside the plugin folder like this

```php
wp_enqueue_script( 'rn_pbwp-particle-js', RN_PBWP_PLUGINS_URL . '/includes/tsparticles.min.js' );
```

and the line 230 of the same file like this

```php
wp_enqueue_script( 'rn_pbwp-particle-js', RN_PBWP_PLUGINS_URL . '/includes/tsparticles.min.js' );
```

I know it's a little tricky but I'll probably checkout this plugin to release a new one with this library.

**Comment by EdgarGR** [comment]
Hi Matteo! 
Thank you very much for wasting your time with my query.

I really don't understand what you raised in the previous message. I will try to see if  a friend understands it and can do it for me.

I have a very basic knowledge of WP and DIVI. Through tutorials I am adapting the web as best I can.

The plugin is not that. It's this other (this is how I installed it): http://cakewp.com/divi-tutorials/add-nice-moving-particles-background-effect/

After this, as I was stretching the particles I added the additional CSS that you told me was probably giving an error.

Do you think that if I install the new plugin it will be easy for me to get the effect like the one you showed me?

Again, thank you so much! I thank you from my heart!

**Comment by matteobruni** [comment]
Ok I checked the plugin, if you are using this plugin.

You can change the particlesjs.php with at line 14 like this

```php
wp_enqueue_script( 'iw_particleJs', plugin_dir_url( __FILE__ ) . '/includes/tsparticles.min.js', false );
```

and delete the particles.js file in the include folder and replace it with the one linked in the previous message.

About the CSS, I try to be clearer.

```css
/*Fondo estrellado alto total sin pixelar*/
.particles-js-canvas-el {
  height: 100vmax !important;
  z-index: 0;
}
```

this is your original css code you included in the issue.

The error is using `.particles-js-canvas-el` instead of its container. So instead of referencing the canvas added by particles.js you should change the height of the div you're adding particles to.

It should be something like this

```css
#fondo_particulas1 {
  height: 100vmax !important;
  z-index: 0;
}
```

If you add scripts directly to DIVI you can change the script you have included from particles.js to tsParticles like explained in the [README](https://github.com/matteobruni/tsparticles/blob/master/README.md)

If you need more help, try upload some screenshot of how you included the particles.js so I can try fix them

**Comment by bop64921** [comment]
Hello @matteobruni im the friend of @EdgarGR helping to try put the particles on the background in our website.

Now i dont using specific Plugin particles, just upload to folder /wp-content/themes/Divi/js the "script.js" downloaded from your CodePen.

And "style.css" in css folder from our Divi theme. 

In Wordpress Admin i charge the scripts using "Header and Plugin Scripts Plugin" and put this scripts charging in the header part:

<script src="http://www.wizardingescaperooms.com/wp-content/themes/Divi/js/tsparticles.min.js"></script>
<script src="http://www.wizardingescaperooms.com/wp-content/themes/Divi/js/script.js"></script>
<script src="https://unpkg.com/tsparticles"></script>
<script src="http://threejs.org/examples/js/libs/stats.min.js"></script>

Then i go to the section of the website i want to show our background and on CSS ID insert "tsparticles" but nothing appears.

What we do wrong?

If it help i can charge some screencaptures.

Thanks for your time, really apreciated.

**Comment by matteobruni** [comment]
Hi @bop64921 

```html
<script src="http://threejs.org/examples/js/libs/stats.min.js"></script>
```

This script is not necessary, it's used for the execution stats you can see in top left corner on codepen

---

```html
<script src="http://www.wizardingescaperooms.com/wp-content/themes/Divi/js/tsparticles.min.js"></script>
<script src="https://unpkg.com/tsparticles"></script>
```

These two scripts seems to be the same thing, you can remove the `unpkg` one.

---

After this you should have a `particlesJS`, or `tsParticles.load` (it's the same), function called. I think it's here

```html
<script src="http://www.wizardingescaperooms.com/wp-content/themes/Divi/js/script.js"></script>
```

but without the code I can't say.

Try these, if it's not working try attach anything can be useful here
