### ISSUE TITLE
How to change particle options on the fly?

### ISSUE THREAD

**Issue by tkhquang** [matteobruni/tsparticles#180]
Hi, thank you for this, I've just tried switching to this from the original version and I can say so far so good.

However I can't seem to find a way to change the config options on the fly. In the original I can do like this:

```js
const pJS = global.pJSDom[0].pJS;

pJS.particles.color.value = currentTheme.color;
pJS.particles.line_linked.color = currentTheme.color;
pJS.particles.shape.stroke.color = currentTheme.bgColor;
pJS.fn.particlesRefresh();
```

How can I achieve the same thing with this?

**Comment by matteobruni** [comment]
Hi @tkhquang 

I changed the old undocumented methods a little bit, to make them clearer.

All the options are now under the `options` property of the main container and the main container has a `refresh()` method

```
const particles = tsParticles.domItem(0);
const options = particles.options;

options.particles.color.value = currentTheme.color;
options.lineLinked.color = currentTheme.color;
options.particles.shape.stroke.color = currentTheme.bgColor;

particles.Refresh();
```

**Comment by tkhquang** [comment]
Thank you @matteobruni , I got it working but I got to change `options.lineLinked.color` to `options.particles.lineLinked.color`.
