### ISSUE TITLE
Problem with loading SVG

### ISSUE THREAD

**Issue by christianjensen2903** [matteobruni/tsparticles#182]
Having a problem with loading a different SVG than the standard one.
Tried with a singleline one:
https://bladenatestsite.weebly.com/files/theme/images/PolyWindTurbine2.svg
and a one which replicated the standard one as close as possible
https://bladenatestsite.weebly.com/files/theme/images/test.svg

**Comment by matteobruni** [comment]
Hi @christianjensen2903,

I've checked the SVG files and they're working, the urls you are testing don't support any origin XHR.

There's a known issue that will be solved in the near future about transform not read from source.

You can checkout the working pens here, if you use particles and svg files from the same host they should work.

https://codepen.io/matteobruni/pen/jOPXZJZ

https://codepen.io/matteobruni/pen/rNVoJRQ

The images are really big so I have to scale them a lot

**Comment by christianjensen2903** [comment]
Ohh that make sense. Thank you so much!
Take care 😊
Br. Christian.

Fra: Matteo Bruni <notifications@github.com>
Svar til: matteobruni/tsparticles <reply@reply.github.com>
Dato: lørdag den 28. marts 2020 kl. 11.02
Til: matteobruni/tsparticles <tsparticles@noreply.github.com>
Cc: christianjensen2903 <cmj290300@gmail.com>, Mention <mention@noreply.github.com>
Emne: Re: [matteobruni/tsparticles] Problem with loading SVG (#182)


Hi @christianjensen2903<https://github.com/christianjensen2903>,

I've checked the SVG files and they're working, the urls you are testing don't support any origin XHR.

There's a known issue that will be solved in the near future about transform not read from source.

You can checkout the working pens here, if you use particles and svg files from the same host they should work.

https://codepen.io/matteobruni/pen/jOPXZJZ

https://codepen.io/matteobruni/pen/rNVoJRQ

The images are really big so I have to scale them a lot
