### ISSUE TITLE
Utilization of tsParticles with a React App [Help?]

### ISSUE THREAD

**Issue by adammesa** [matteobruni/tsparticles#183]
**The Problem**
How does (a novice react developer) use this library with a TypeScript react app? (Created with create-react-app's typescript version)

**Solution**
1. Install `yarn add tsparticles`
2. Add `import tsParticles from 'tsparticles';` to the top of the file that you want to have tsParticles (tsParticles should not have type any)
3. Call tsParticles from react component body to attach it to a jsx-rendered div component

Some documentation for use web apps would be greatly appreciated! 

**Additional context**
My development environment is **NextJS/React/TypeScript,** would greatly appreciate using this to add an extra "glow" to the UI. NextJS isn't a single-page web app, so globally importing the JS as mentioned in the UI is expensive for an effect in use on only a few pages.

Another dependency I used had a similar [TypeScript-lacking-types issue](https://github.com/nzambello/react-csv-reader/issues/37#issuecomment-602054916). That plugin, however, also featured documentation for using with React. 

**Additional context**

**Comment by matteobruni** [comment]
Hi @adammesa,

I'm currently working on a react-ready version of this library trying to merge into react-particles-js.

The repository is this https://github.com/matteobruni/react-particles-js, a fork of the original one with an open PR.

If you want to see current work, the 1.11.0 update it's not implemented yet, I'll bring it asap.

**Comment by adammesa** [comment]
@matteobruni that looks just like what I need, thank you! 

I'm going to sit on it for a while (I have a backlog of other items), but thank you for all your hard work (and super-frequent updates!)

**Comment by matteobruni** [comment]
Hi again @adammesa,

I've just released the 1.11.1 version with a little bug fix for images as shape. I've updated the react repositories as well, you can use them as sample. They are working fine now.

**Comment by matteobruni** [comment]
Version 3.0 of [react-particles-js](https://github.com/Wufe/react-particles-js) uses tsParticles
