### ISSUE TITLE
Changing Color via getting a css variable

### ISSUE THREAD

**Issue by matteobruni** [matteobruni/tsparticles#195]
> Is there any way to change the color of the particles by getting a css variable? I have tried this:
> 
> ```js
> const particlesColor = getComputedStyle(document.body);
> pJSDom[0].pJS.particles.color.value = particlesColor.getPropertyValue('--particlesColor');
> pJSDom[0].pJS.fn.particlesRefresh()
> ```
> 
> But I get the error : `a.color.hsl is undefined`

Issue https://github.com/VincentGarreau/particles.js/issues/434#issue-590917998 from the original project by @ZigZagZat

Hello, I'm maintaining this project and the other was abandoned years ago. Can you explain me more about this feature?

I think I have all ready for this.

**Comment by matteobruni** [comment]
With this library you could do this:

```javascript
const particlesColor = getComputedStyle(document.body);
const container = tsParticles.domItem(0);

container.loadOptions({
    particles: {
         color: {
               value: particlesColor.getPropertyValue('--particlesColor')
         }
    }
});
container.refresh();
```

Everything should work as you requested

**Comment by TheE** [comment]
@matteobruni Unfortunately, the above solution no longer works.  Using tsParticles `1.18.11`, I get the following error when running your code:

```
Uncaught TypeError: container.loadOptions is not a function
    <anonymous> debugger eval code:4
```
Any help?

**Comment by matteobruni** [comment]
Hi @TheE,

This was a really old thread that I forgot

Anyway, now you can use `container.options.load` method.

**Comment by TheE** [comment]
Many thanks, that works perfectly.

In case anybody else has the same problem, below is working javascript:

```Javascript
function setup_particles() {
     var color_var = bodyStyle.getPropertyValue('--particles-color').trim();

     tsParticles.loadJSON('site-canvas', 'default.json')
         .then((container) => {
             container.options.load({
                 particles: {
                     color: {
                         value: color_var
                     },
                     line_linked: {
                         color: {
                             value: color_var
                         }
                     }
                 }
             });
             container.refresh();
         })
         .catch((error) => {
             console.error(error)
         })
 } 
```
Then one can easily change the value of the variable to add a simple dark mode:
```CSS
--particles-color: #111;

@media (prefers-color-scheme: dark) {
    --particles-color: #D1D1D1;
}
```

**Comment by abhishekkokate** [comment]
hey i am getting "Home.js:143 Uncaught TypeError: react_tsparticles__WEBPACK_IMPORTED_MODULE_1___default(...).loadJSON is not a function" this error can u help me with that. (i am using react-tsparticle)

**Comment by matteobruni** [comment]
> hey i am getting "Home.js:143 Uncaught TypeError: react_tsparticles__WEBPACK_IMPORTED_MODULE_1___default(...).loadJSON is not a function" this error can u help me with that. (i am using react-tsparticle)

Open a new issue about that, with a sample to reproduce the issue.
