### ISSUE TITLE
Mouse hover color changing

### ISSUE THREAD

**Issue by matteobruni** [matteobruni/tsparticles#206]
An option to change color to particles on the mouse hover event. This can be merged with the existing bubble feature that already has opacity and size

**Comment by nila99** [comment]
Could I work on this?

**Comment by matteobruni** [comment]
Sure, just use dev branch as base please, the new features are there. If you need help you can also join Slack

**Comment by TylerBurnett** [comment]
This looks like a good opportunity to further implement the spatial grid! 
Currently, we're starting to port over to a faster neighbor detection system based on a grid-like structure.

If anything it might be easier for you to implement the behavior with the new system! In my current PR, there are updates to its functionality. Which makes it easier to check radius. it can be done something like this:

`for (const p2 of container.particles.spatialGrid.queryRadius(p1.position, radius)) { 
interact.
}`

Note this hasn't been merged as of yet, but if you could implement this as your distance checking it would be a great help in the integration of the system.

**Comment by matteobruni** [comment]
This feature is added to the `bubble` mode. I did some tests and seems ok. The spatial grid was not used yet.

**Comment by nila99** [comment]
I can try to implement the spatial grid. However, I am running into an issue. While I was able to test before, now when i try to run npm run build i get this "error File '/Desktop/tsparticles/tests/options.ts' is not under 'rootDir' '/Desktop/tsparticles/src'. 'rootDir' is expected to contain all source files." do you know what might be the issue?

**Comment by matteobruni** [comment]
Sorry I broke `dev` branch! Now should be fine.

**Comment by matteobruni** [comment]
You can implement the spatial on bubble mode, it's fine. If you find any bug you can try fix it. If you need help you can ask on Slack
