### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by matteobruni** [matteobruni/tsparticles#229]
This project is becoming huge and some unit tests could improve testing process.

The critical tests are about options that are a lot and have a lot of values and some properties can have different values.

Some tests about `tsParticles` initializer can be made too, or something about the core functionalities.

For options `mocha` and `chai` seem fine, about the animation process I really don't know if they can be used.

**Comment by PieceMaker** [comment]
I'll start work on this one.

I dug through the library this evening and think I have a grasp on the structure and what it might take to start testing some of the pieces. My plan is to build the structure and write tests for `Utils/Utils.ts`. Once this is done, I'll see what other utilities I can write tests for. Once this is done, I should have a good enough grasp that I can start writing tests for `Particle.ts`.

**Comment by matteobruni** [comment]
> I'll start work on this one.
> 
> I dug through the library this evening and think I have a grasp on the structure and what it might take to start testing some of the pieces. My plan is to build the structure and write tests for `Utils/Utils.ts`. Once this is done, I'll see what other utilities I can write tests for. Once this is done, I should have a good enough grasp that I can start writing tests for `Particle.ts`.

Perfect, Utils/ColorUtils.ts should be another easy file to test if you want.
If you need any help feel free to join the project's Slack
