### ISSUE TITLE
Minimum Size without animation

### ISSUE THREAD

**Issue by robhuska** [matteobruni/tsparticles#258]
**Is your feature request related to a problem? Please describe.**
Not a problem, just a request

**Describe the solution you'd like**
I would like to set a range for the sizes. Maybe `particles.size.value` accepts a `Number / Object`

Number would be for what it is now, a maximum size. Object could be:
```
{
  'min': 10,
  'max': 35
}
```

**Describe alternatives you've considered**
No alternatives...

**Additional context**
This is a thread from the repo this project was branched from that had no response.
https://github.com/VincentGarreau/particles.js/issues/320

**Comment by matteobruni** [comment]
Hi @robhuska, this feature was made some time ago.

I've seen now the lack in the wiki, I'll upgrade it ASAP.

The syntax is a little bit different.

```json
"size": {
  "value": 35,
  "random": {
    "enable": true,
    "minimumValue": 10
  }
}
```

This `minimumValue` won't affect the `animation.minimumValue` (or `anim.size_min` for old configurations) btw.

The random range with this configuration will be from `size.random.minimumValue` to `size.value`, the animation can be pushed beyond these limits.

**Comment by robhuska** [comment]
Wow!!! Fantastic! Thanks for keeping this up-to-date.

**Comment by Corfias** [comment]
@matteobruni Hi Matteo,

I am having a similar issue, I am using an image for the particle but I can't get the size to be a set minimum. Currently, there are some very small images appearing. 

Below is the code, I would appreciate the help.

Thank you!

`{
  "particles": {
    "number": {
      "value": 25,
      "density": {
        "enable": true,
        "value_area": 600
      }
    },
    "color": {
      "value": "#fff"
    },
    "shape": {
      "type": "image",
      "stroke": {
        "width": 0,
        "color": "#000000"
      },
      "polygon": {
        "nb_sides": 5
      },
      "image": {
        "src": "https://drive.google.com/uc?id=1Y9tXp6dG-TWrvni8CgHmyNvnIPgTGwDp",
        "width": 200,
        "height":200
      }
    },
    "opacity": {
      "value": 1,
      "random": true,
      "anim": {
        "enable": false,
        "speed": 1,
        "opacity_min": 0.1,
        "sync": false
      }
    },
    "size": {
      "value": 20,
      "random": true,
      "minimumValue": 20,
      "anim": {
        "enable": false,
        "speed": 2,
        "size_min": 10,
        "sync": true
      }
    },
    "line_linked": {
      "enable": false,
      "distance": 500,
      "color": "#ffffff",
      "opacity": 0.4,
      "width": 2
    },
    "move": {
      "enable": true,
      "speed": 2,
      "direction": "top",
      "random": true,
      "straight": true,
      "out_mode": "out",
      "bounce": false,
      "attract": {
        "enable": false,
        "rotateX": 600,
        "rotateY": 2604.1872173865
      }
    }
  },
  "interactivity": {
    "detect_on": "window",
    "events": {
      "onhover": {
        "enable": false,
        "mode": "repulse"
      },
      "onclick": {
        "enable": false,
        "mode": "repulse"
      },
      "resize": true
    },
    "modes": {
      "grab": {
        "distance": 400,
        "line_linked": {
          "opacity": 0.5
        }
      },
      "bubble": {
        "distance": 400,
        "size": 4,
        "duration": 0.3,
        "opacity": 1,
        "speed": 3
      },
      "repulse": {
        "distance": 200,
        "duration": 0.4
      },
      "push": {
        "particles_nb": 4
      },
      "remove": {
        "particles_nb": 2
      }
    }
  },
  "retina_detect": true
}`

**Comment by matteobruni** [comment]
> @matteobruni Hi Matteo,
> 
> I am having a similar issue, I am using an image for the particle but I can't get the size to be a set minimum. Currently, there are some very small images appearing.
> 
> Below is the code, I would appreciate the help.
> 
> Thank you!
> 
> ```
>   "particles": {
>     "number": {
>       "value": 25,
>       "density": {
>         "enable": true,
>         "value_area": 600
>       }
>     },
>     "color": {
>       "value": "#fff"
>     },
>     "shape": {
>       "type": "image",
>       "stroke": {
>         "width": 0,
>         "color": "#000000"
>       },
>       "polygon": {
>         "nb_sides": 5
>       },
>       "image": {
>         "src": "https://drive.google.com/uc?id=1Y9tXp6dG-TWrvni8CgHmyNvnIPgTGwDp",
>         "width": 200,
>         "height":200
>       }
>     },
>     "opacity": {
>       "value": 1,
>       "random": true,
>       "anim": {
>         "enable": false,
>         "speed": 1,
>         "opacity_min": 0.1,
>         "sync": false
>       }
>     },
>     "size": {
>       "value": 20,
>       "random": true,
>       "minimumValue": 20,
>       "anim": {
>         "enable": false,
>         "speed": 2,
>         "size_min": 10,
>         "sync": true
>       }
>     },
>     "line_linked": {
>       "enable": false,
>       "distance": 500,
>       "color": "#ffffff",
>       "opacity": 0.4,
>       "width": 2
>     },
>     "move": {
>       "enable": true,
>       "speed": 2,
>       "direction": "top",
>       "random": true,
>       "straight": true,
>       "out_mode": "out",
>       "bounce": false,
>       "attract": {
>         "enable": false,
>         "rotateX": 600,
>         "rotateY": 2604.1872173865
>       }
>     }
>   },
>   "interactivity": {
>     "detect_on": "window",
>     "events": {
>       "onhover": {
>         "enable": false,
>         "mode": "repulse"
>       },
>       "onclick": {
>         "enable": false,
>         "mode": "repulse"
>       },
>       "resize": true
>     },
>     "modes": {
>       "grab": {
>         "distance": 400,
>         "line_linked": {
>           "opacity": 0.5
>         }
>       },
>       "bubble": {
>         "distance": 400,
>         "size": 4,
>         "duration": 0.3,
>         "opacity": 1,
>         "speed": 3
>       },
>       "repulse": {
>         "distance": 200,
>         "duration": 0.4
>       },
>       "push": {
>         "particles_nb": 4
>       },
>       "remove": {
>         "particles_nb": 2
>       }
>     }
>   },
>   "retina_detect": true
> }```
> ```

Hi @Corfias, I've seen your config and there's an error:

```
"random": true,
"minimumValue": 20,
```

The right syntax is:

```
"random": {
    "enable": true,
    "minimumValue": 20
}
```

`random` property accepts `boolean` or `object` values, the `object` has the two properties I wrote above, the `boolean` has no `minimumValue` since it's not specified.

**Comment by Corfias** [comment]
@matteobruni Thank you for the response.

I have made the changes with little success, now the code doesn't seem to work. Sorry I am not very skilled in this space.

The new code is ` {
 "particles": {
    "number": {
      "value": 25,
      "density": {
        "enable": true,
        "value_area": 600
      }
    },
    "color": {
      "value": "#fff"
    },
    "shape": {
      "type": "image",
      "stroke": {
        "width": 0,
        "color": "#000000"
      },
      "polygon": {
        "nb_sides": 5
      },
      "image": {
        "src": "https://drive.google.com/uc?id=1Y9tXp6dG-TWrvni8CgHmyNvnIPgTGwDp",
        "width": 200,
        "height":200
      }
    },
    "opacity": {
      "value": 1,
      "random": true,
      "anim": {
        "enable": false,
        "speed": 1,
        "opacity_min": 0.1,
        "sync": false
      }
    },
    "size": {
      "value": 20,
     "random": {
    "enable": true,
    "minimumValue": 20
}
      "anim": {
        "enable": false,
        "speed": 2,
        "size_min": 10,
        "sync": true
      }
    },
    "line_linked": {
      "enable": false,
      "distance": 500,
      "color": "#ffffff",
      "opacity": 0.4,
      "width": 2
    },
    "move": {
      "enable": true,
      "speed": 2,
      "direction": "top",
      "random": true,
      "straight": true,
      "out_mode": "out",
      "bounce": false,
      "attract": {
        "enable": false,
        "rotateX": 600,
        "rotateY": 2604.1872173865
      }
    }
  },
  "interactivity": {
    "detect_on": "window",
    "events": {
      "onhover": {
        "enable": false,
        "mode": "repulse"
      },
      "onclick": {
        "enable": false,
        "mode": "repulse"
      },
      "resize": true
    },
    "modes": {
      "grab": {
        "distance": 400,
        "line_linked": {
          "opacity": 0.5
        }
      },
      "bubble": {
        "distance": 400,
        "size": 4,
        "duration": 0.3,
        "opacity": 1,
        "speed": 3
      },
      "repulse": {
        "distance": 200,
        "duration": 0.4
      },
      "push": {
        "particles_nb": 4
      },
      "remove": {
        "particles_nb": 2
      }
    }
  },
  "retina_detect": true
}`

**Comment by matteobruni** [comment]
it's missing a comma here

```
"random": {
    "enable": true,
    "minimumValue": 20
}, // here
```

**Comment by Corfias** [comment]
Thank you @matteobruni, the code did fix the error but the minimum doesn't seem to be applying, there is still very small images. Any other ideas?

**Comment by matteobruni** [comment]
I've seen now, you set the minimum value to the same size of value, you can disable the random option if you don't want that feature with `"random": false`.

That should fix your issue, about the minimum value with random I'll make some tests, what version are you using?

**Comment by Corfias** [comment]
I will test the random as false but I do like that feature. 

I am not sure, I could find out but it built into a webpage builder (Elementor)

**Comment by matteobruni** [comment]
Probably that builder has an older version that doesn't support minimumValue on random, I tested it again and it's fine

**Comment by Corfias** [comment]
What version is the new one?

**Comment by matteobruni** [comment]
Nope, 1.13.9 it’s the latest.

The Particles.js package (abandoned, not mine) has version 2.0.0

**Comment by Corfias** [comment]
Oh, this update for the minvalue won't be in parcticles.js?

**Comment by matteobruni** [comment]
> Oh, this update for the minvalue won't be in parcticles.js?

Nope, it's a tsParticles feature. I took Particles.js codebase and added features and bug fixes. So what's on Particles.js is here but not everything is here can be used there

**Comment by Corfias** [comment]
Damn, I will suggest to the plugin creator for the Wordpress to possibly incorporate your version if possible unless you would know a way to assist me with this?

**Comment by matteobruni** [comment]
The only other way is finding the particlesJS references and replace them, javascript files and javascript code but this can be a little tricky.

I try to explain it easily:

- Find the particles.js file and replace it with tsparticles.js file (https://cdn.jsdelivr.net/npm/tsparticles@1.13.9/dist/tsparticles.min.js) if you need it
- Replace the `<script>` tag with particles.js with tsparticles.js (tsparticles.min.js)
- Search `particlesJS` in javascript files and replace it with `tsParticles.load`

These steps should make it work but if there's some customization over particles.js these couldn't be enough.

Having the support of the plugin creator should be the easiest way. If you can provide me a link I try to give more information about this project to the creator.
