### ISSUE TITLE
Particle sizes are larger on mobile devices

### ISSUE THREAD

**Issue by crutchcorn** [matteobruni/tsparticles#281]
**Describe the bug**

On this repo:

https://github.com/crutchcorn/gitshark-website/commit/67af916535b42bc235751b139ccf6c9fde2b452e

When loading from desktop, I get the following visuals of the various sizes of particles:

![image](https://user-images.githubusercontent.com/9100169/80760800-59b36500-8aee-11ea-800d-261209b51a82.png)

However, when I use Chrome's "Toggle Device Toolbar" (or even use a mobile device [Samsung S10+ using Chrome]) and refresh the page, I get the bubbles to be much much larger with the same config settings:

![image](https://user-images.githubusercontent.com/9100169/80760907-7f406e80-8aee-11ea-8a37-62bd5c107721.png)

I would expect these particle sizes to be the same. This is the config I'm passing to the tsParticles:

https://github.com/crutchcorn/gitshark-website/blob/67af916535b42bc235751b139ccf6c9fde2b452e/src/components/shark-background/shark-background.jsx#L102-L175

**Comment by crutchcorn** [comment]
Posted prematurely. Editing right now

**Comment by matteobruni** [comment]
For a temporary fix you can disable the retina detect option. I'll work on this as soon as possible

**Comment by matteobruni** [comment]
tsParticles 1.13.6 have this fix, react-particles-js will be updated with this fix too in 3.2.1.

**Comment by crutchcorn** [comment]
I swear you are the fastest maintainer I've ever seen. You're amazing

**Comment by matteobruni** [comment]
You caught me still wake, I can't go bed with a bug open!
