### ISSUE TITLE
Phaser/PixiJS integration

### ISSUE THREAD

**Issue by jdnichollsc** [matteobruni/tsparticles#285]
**Is your feature request related to a problem? Please describe.**
It would be awesome if we can integrate this with another frameworks like PixiJS and Phaser

**Describe the solution you'd like**
I would love the possibility to use this library with another frameworks

**Describe alternatives you've considered**
Creating plugins for these frameworks

**Comment by matteobruni** [comment]
Hello,

I don't know anything about PixiJS or Phaser, can you explain more about the request?

**Comment by jdnichollsc** [comment]
I have examples here: https://codepen.io/collection/AQWqbV
These frameworks are used to create games, so having an integration with this library would be very awesome for creating games with this kind of particles! I was wondering if we can inject the canvas generated by Phaser or something like that to use with it, what do you think?

**Comment by matteobruni** [comment]
There are a lot of issues for that, these frameworks supports webGL and this library don't, they have its own draw loop that will probably won't work well, this draw loop clears the canvas to redraw all the particles.

Using those frameworks should be the easies way but for the moment I don't want to add any dependency like that. I want to keep everything easy and ready to use.

**Comment by jdnichollsc** [comment]
excellent, thanks for the comments!
