### ISSUE TITLE
Pausing does not work in FireFox

### ISSUE THREAD

**Issue by crutchcorn** [matteobruni/tsparticles#296]
**Describe the bug**

If you open https://gitshark.dev on FireFox, then press "pause", it doesn't actually stop the particles

Source code for that site, as always, can be found at:
https://github.com/crutchcorn/gitshark-website

With the pausing code found at:

https://github.com/crutchcorn/gitshark-website/blob/master/src/components/shark-background/shark-background.jsx#L29

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser FireFox 75

**Comment by matteobruni** [comment]
I tried your website in two different Firefox 75.0, one on macOS and one on Win10, but everything worked as expected. The Play/Pause button paused and resumed the animation correctly.

**Comment by crutchcorn** [comment]
I've noticed that it _will_ pause, but not after the first reload. If I fresh reload the page, then try to "pause on Firefox", it won't do so. But then if I "Play" and try to "pause" later, it _will_ work those subsequent times

![bubbles_bug](https://user-images.githubusercontent.com/9100169/81088857-6e0dae00-8eb0-11ea-9f19-8e625474ed7e.gif)

**Comment by matteobruni** [comment]
I noticed that if you wait some seconds to pause it works, I'll investigate further this issue.
The container start method is asynchronous, probably it's caused by that.

**Comment by matteobruni** [comment]
@crutchcorn can you try 1.14.0-beta.0 version? That version should fix the issue.

**Comment by crutchcorn** [comment]
@matteobruni I'm getting the following errors from `react-particles` when using tsParticles via yarn resolution:

```
 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'tsparticles/dist/Classes/Container' in 'C:\Users\crutchcorn\git\GitGui\site\node_modules\react-particles-js\cjs'

File: node_modules\react-particles-js\cjs\particles.js


 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'tsparticles/dist/Classes/Options/Options' in 'C:\Users\crutchcorn\git\GitGui\site\node_modules\react-particles-js\cjs'

File: node_modules\react-particles-js\cjs\particles.js
```

Replacing the `Class/Options/Options` was easy enough:

```
node_modules/tsparticles/dist/Options/Classes/Options.js
```

But then I don't know what to do for `Classes/Container`

**Comment by matteobruni** [comment]
Ah yes, I changed the folder structure in 1.14.0, I’ll create soon an alias for compatibility

**Comment by crutchcorn** [comment]
Gimme a ping when you do so and I'll test again :) Thanks again for taking a look at this all so quickly

**Comment by matteobruni** [comment]
1.14.0-beta.2 should fix the compatibility with react-particles-js

**Comment by crutchcorn** [comment]
Not only did it fix the issues with FF pausing, but it caused other timing issues with pausing as mentioned here:

https://github.com/crutchcorn/gitshark-website/commit/8abb3628128e0de4a280a66de389294242d324bb#r38868121
