### ISSUE TITLE
Configuration for Multiple Colours

### ISSUE THREAD

**Issue by jessebett** [matteobruni/tsparticles#301]
Is it possible to configure so that there are multiple different colours for particles? 
For example red, green, blue particles all interacting/colliding in the same environment.

I looked at the presets in the example page and could not find a configuration that suggests this is possible.

**Comment by matteobruni** [comment]
Yes it’s possible, the `color` value can be an array too.

This sample uses this behavior: https://codepen.io/matteobruni/pen/MWaePMa

If you want to see more pens I maintain a collection too: https://codepen.io/collection/DPOage

**Comment by jessebett** [comment]
Great thanks! Might be worth to add as a preset example showing array of `color` for easier discovery.
