### ISSUE TITLE
Link Triangles

### ISSUE THREAD

**Issue by matteobruni** [matteobruni/tsparticles#312]
A feature request in the original project was this: https://github.com/VincentGarreau/particles.js/issues/18

Filling the triangle shape made by linked lines, obviously customizable

**Comment by mobbjelly** [comment]
Hi, is it somehow possible for filling not all triangle shapes, but some random triangle shapes?

**Comment by matteobruni** [comment]
I’ve checked and for now is not possible but it’s a bug because it should be.

I’ll fix it ASAP

This configuration anyway will be a little tricky.
