### ISSUE TITLE
Occasionally "squished" particles

### ISSUE THREAD

**Issue by robhuska** [matteobruni/tsparticles#318]
So this isn't really a bug, more of an "any ideas of how to resolve?" type of thing...

Very infrequently onload my particles are "squished". I was wondering if anyone had any sort of tips to prevent this from ever happening? My assumption is it is because the image, on the left in the screen shots below, loads too slow occasionally. So when it loads in the height of the container changes all of a sudden and they get stretched.

Occasionally looks like this:
![image](https://user-images.githubusercontent.com/2412155/82073670-91520d80-96a7-11ea-84ac-2cd2491419fe.png)

Should look like this:
![image](https://user-images.githubusercontent.com/2412155/82073722-a2028380-96a7-11ea-8339-771476e17583.png)

How I am loading it:
```
const particles = document.querySelectorAll('.add-particles');

particles.forEach((el, i) => {
  let particleDiv = document.createElement('div');
  const id = `particles-${i}`;

  particleDiv.classList.add('particles');
  particleDiv.setAttribute('id', id);
  el.insertBefore(particleDiv, el.firstChild);

  /* ---- tsParticles.js config ---- */
  tsParticles.load(id, {
    // my configuration
  });
})
```

**Comment by matteobruni** [comment]
Hello @robhuska, I can study a resize event that could solve this issue.

Anyway you can solve it calling `.refresh()` on the particles container.

The `tsParticles.load` is an `async` function that return a `Promise<Container>`.

`Container` is the class that have the `.refresh()` method.

If you store all the containers you are creating you can then refresh all of them when image load event occurs.

---

Anyway, why are you using more than one container? I don't recommend it because it can use too much CPU.

**Comment by robhuska** [comment]
The answer to you last question is that we have built a site that has modules that could potentially have particles behind the content. We will be maintaining the content so we can definitely limit the amount of times used on a page, but the potential is there.

I will try the image load event first, that seem easiest.

**Comment by robhuska** [comment]
wrapping it in a `window.addEventlistener('load', () => {});` does the trick it seems. At least I haven't been able to make it happen since. But it is really infrequent to begin with.

Also, not related, but since I updated to the latest `1.14.1` I seem to get a console log stating an error withing tsparticles.
![image](https://user-images.githubusercontent.com/2412155/82082537-31af2e80-96b6-11ea-96f7-1f9c004cf9e2.png)

**Comment by matteobruni** [comment]
About that console message, I already noticed but I haven't started looking yet, it's nothing critical. If you are not using images particles you can remove the `image` object in `shape` section, it should fix the error.

**Comment by robhuska** [comment]
No problem about the console.log, just making sure you knew.
Here is my config, i am not using the `image` object
```
      tsParticles.load(id, {
        "particles": {
          "number": {
            "value": 15,
            "density": {
              "enable": false,
            }
          },
          "color": {
            "value": ["#66b2e8", "#d6992b", "#4d9c2e"]
          },
          "shape": {
            "type": "circle",
          },
          "opacity": {
            "value": 0.7,
            "random": false,
          },
          "size": {
            "value": 50,
            "random": {
              "enable": true,
              "minimumValue": 20
            }
          },
          "line_linked": {
            "enable": false,
          },
          "move": {
            "enable": true,
            "speed": 3,
            "direction": "none",
            "random": true,
            "straight": false,
            "out_mode": "out",
            "bounce": false,
            "attract": {
              "enable": false,
            }
          }
        },
        "interactivity": {
          "detect_on": "canvas",
          "events": {
            "onhover": {
              "enable": false,
            },
            "onclick": {
              "enable": false,
            },
            "resize": true
          }
        },
        "retina_detect": true
      });
```

**Comment by matteobruni** [comment]
Ok, I'll have a look on that, thanks

**Comment by robhuska** [comment]
Thanks! Also, thanks for quick responses to issues, and branching and maintaining this plugin!

Oh, that's nice! I know when I was using the old one i had issues removing all those things.
