### ISSUE TITLE
Typing Svelte component

### ISSUE THREAD

**Issue by longnguyen2004** [matteobruni/tsparticles#3265]
### Contact Details

nguyen.long.908132@gmail.com

### What is your request?

When importing `svelte-particles`, TypeScript can't provide type checking for the component, since it doesn't look at the source file. So we need to type it ourselves.

Reference: https://github.com/sveltejs/rfcs/blob/master/text/0005-svelte-component-interface.md
NOTE: Use `SvelteComponentTyped` instead of `SvelteComponent` (see https://svelte.dev/blog/whats-new-in-svelte-december-2020)

### Version

1.41.1

### Which library are you using?

Svelte (svelte-particles)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
The documentation you sent is for `class` components but `svelte-particles` is using hooks-style syntax. Do you know how to generate types with that?

**Comment by longnguyen2004** [comment]
It looks like a normal Svelte component to me, not sure what you mean by hooks-style syntax here.

**Comment by matteobruni** [comment]
The `svelte-particles` component has no classes, I don't have any SvelteComponent extended, so I cannot change the base class. It's just a function with `exports`.

**Comment by longnguyen2004** [comment]
All Svelte components are converted to a class during the compile step. You can see this with the Svelte REPL. In the JS output, it creates a class `App` that extends `SvelteComponent`.
Anyway, here's what I came up with
```ts
import { SvelteComponentTyped } from "svelte";
import { Engine, Container, IOptions, SingleOrMultiple, RecursivePartial } from "tsparticles";

declare module "svelte-particles" {
  export default class extends SvelteComponentTyped<
    {
      id: string; url: string;
      options: SingleOrMultiple<RecursivePartial<IOptions>>;
    },
    {
      particlesInit: Engine;
      particlesOptions: { particles: Container };
    },
    {}
  > {}
}
```

I could try to submit a PR for this, but I need to figure out how all of this work first :) You can take this as a starting point though.

**Comment by longnguyen2004** [comment]
Fixed!
