### ISSUE TITLE
Okay but where is the file

### ISSUE THREAD

**Issue by alenieto97** [matteobruni/tsparticles#329]
I want to migrate from jsparticles since is has some problems, but cant find the tsparticles.js file anywhere. If you put it somewhere visible it would be nice, since I dont know how to use webkit to install it on the client side with import or anything

**Comment by matteobruni** [comment]
Hi @alenieto97 

You can download the file from [jsDelivr](https://www.jsdelivr.com/package/npm/tsparticles) or [cdnjs](https://cdnjs.com/libraries/tsparticles).
If you cloned the repository you can run `npm run build` or `yarn build` in the repository folder and the `dist` folder contains the compiled files.
You can checkout the [release tab](https://github.com/matteobruni/tsparticles/releases) here on GitHub too, the file should be there too.

If you need more help let me know
