### ISSUE TITLE
Worse than particles.js - continuation

### ISSUE THREAD

**Issue by koxu1996** [matteobruni/tsparticles#3398]
### Issue

This is continuation of https://github.com/matteobruni/tsparticles/issues/2936 where I reported that tsparticles is laggy and unusable. Happily you found the bug and now animation is smooth, however **there are still some basic bugs that are not present in particles.js**. This time I would like to show you what happens if you resize canvas area: https://www.youtube.com/watch?v=zd5J12lOs4s

Here are codepens from the video:
- [particles.js](https://codepen.io/andrzej1_1/pen/ExbxNdX)
- [tsParticles](https://codepen.io/andrzej1_1/pen/MWOzVjP)

Please take a look, hope you can fix it.

### Version

1.41.5

### Which library are you using?

Vanilla (tsparticles)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
Duplicated of #1587
