### ISSUE TITLE
Cannot read property nextFrame of undefined

### ISSUE THREAD

**Issue by marbemac** [matteobruni/tsparticles#349]
**Describe the bug**

`drawer` is not guaranteed to be available, which can lead to `nextFrame` undefined errors.

**To Reproduce**

This is difficult to reproduce, as it's a race-y type situation.

Caveat here that I don't know much about tsParticles internals, but it seems that `drawer` is typed as always available on the class (https://github.com/matteobruni/tsparticles/blob/ea89bfc15be6003cb59dcd77252fe6a4a20f32fc/src/Core/Container.ts#L35) and yet it's deleted in some cases (https://github.com/matteobruni/tsparticles/blob/ea89bfc15be6003cb59dcd77252fe6a4a20f32fc/src/Core/Container.ts#L198).

If it's possible that drawer is undefined on the class at any point, I suggest that it be typed as optional and cases like https://github.com/matteobruni/tsparticles/blob/ea89bfc15be6003cb59dcd77252fe6a4a20f32fc/src/Core/Container.ts#L147, which happen in a separate closure and thus might occur on the tick after destroy (which could in turn cause the issue in the screenshot below), be protected appropriately e.g. `this.drawer?.nextFrame(t)`.

**Screenshots**

From our error reporter:

<img width="1172" alt="Screen Shot 2020-05-28 at 8 38 31 PM" src="https://user-images.githubusercontent.com/847542/83211696-6776fd00-a123-11ea-91ce-105057ff2a1c.png">

**Desktop (please complete the following information):**

Not browser specific.

**Comment by matteobruni** [comment]
Hi, thanks for the report.

Yes, your thoughts are correct, that property should handle optional.

It'll be fixed in the upcoming 1.15.0, if you want to submit a PR with the bug fix feel free to do it

**Comment by marbemac** [comment]
Thank you @matteobruni!
