### ISSUE TITLE
rotate svg to match particle path

### ISSUE THREAD

**Issue by jeffgoh** [matteobruni/tsparticles#408]
Currently, particles don't have the notion of "forward", for example, a circle or star can move in any direction, but airplanes (for example) can't move sideways IRL.

I'd like to be able to rotate an SVG so that the object moves "forward" in random directions

Currently, I've set it to move left-to-right ("right") and set the rotation to be fixed, but this is kinda boring.

Generally, I'm asking for particles to have a sense of direction so I can get my planes to fly criss-cross patterns (also cars, people, etc).

**Comment by matteobruni** [comment]
Hi @jeffgoh, thanks for the suggestion.

I've released now the `1.17.0-alpha.2` version with this feature, can you give me a feedback if everything is working as expected?

**Comment by jeffgoh** [comment]
wow - I got busy with other stuff - thanks for the quick turnaround! will test and revert, but I expect that you've done so already.

**Comment by jeffgoh** [comment]
Brilliant - works perfectly - not that I have any practical use for this, lol - https://www.lightspeed.com.sg/test/tsparticles/demo/
