### ISSUE TITLE
Not showing correctly on first load

### ISSUE THREAD

**Issue by matteobruni** [matteobruni/tsparticles#43]
@mresmaeili I've seen your [issue](https://github.com/VincentGarreau/particles.js/issues/418)

Can you check if this version has the same problem? I don't understand where's the problem, the link you attached there is fine for me.

**Comment by mresmaeili** [comment]
Yes, it's a bit strange because sometimes it happens sometimes works fine.
I'm not that much lucky so it didn't work for the client now I'm here!
I'll test this version and let you know about it
regards
