### ISSUE TITLE
Wordwrap text feature?

### ISSUE THREAD

**Issue by lectair** [matteobruni/tsparticles#474]
I think it would be a nice idea to add a functionality to wrap the text if the line is too big, and allowing to change the maximum characters per line.

**Comment by matteobruni** [comment]
Unfortunately `<canvas>` doesn't support newline so it's needed a text draw for every line which is a little too heavy in my opinion.

I suggest a custom shape for that, you can find the documentation here:

https://github.com/matteobruni/tsparticles/wiki/Create-a-tsParticles-Plugin#creating-a-custom-shape

A `multilinetext` custom shape could be the easiest way. I'll make it as an external plugin like `spiral`, `bubble` and `heart`.

**Comment by matteobruni** [comment]
Hi @lectair 

I released a first version of that shape here: https://cdn.jsdelivr.net/npm/tsparticles-shape-multiline-text@1.1.2/dist/tsparticles.shape.multiline-text.min.js (it's on `npm` too)

You can see a sample here: https://codepen.io/matteobruni/pen/abdwNgv

The centering issue will be fixed when 1.2.0 version will come out with 1.17.0
