### ISSUE TITLE
Mouse hover/click attract mode

### ISSUE THREAD

**Issue by matteobruni** [matteobruni/tsparticles#504]
A mouse `attract` mode is interesting, which attracts particles to the current mouse position (hover) or the mouse click position (click/touch).

For the `hover` event the attraction is active for all the time the mouse is hover, for the `click`/`touch` event it uses the duration, like the `repulse` mode.

This mode should have an attraction speed option at least, and a duration option for `click`/`touch` events.

**Comment by Sanil2108** [comment]
I would love to contribute to this if it is still open!

**Comment by matteobruni** [comment]
Hi @Sanil2108 welcome, yes it's still open this issue, I've not started this yet.

Please use `dev` branch because it has the 1.17 version and target the PR to the same branch, thanks.
