### ISSUE TITLE
Example params/generated params creates errors with enum types (and possibly others)

### ISSUE THREAD

**Issue by BenAOlson** [matteobruni/tsparticles#508]
Using the example params from the readme for the React version, or any of the params generated from https://particles.matteobruni.it/ cause with all of the enum types (that I can tell).

Example [CodeSandbox](https://codesandbox.io/s/shy-tdd-c6jvx)

**Comment by matteobruni** [comment]
I'm working on options in the upcoming 1.17.0 release, I'll fix this in that version. Thanks for reporting!

**Comment by matteobruni** [comment]
1.17.0-alpha.13 should fix the issue, I've found also a bad sample with a non existing property. I'll fix that ASAP.
