### ISSUE TITLE
Make it possible to pass in a DOM Element instead of an id

### ISSUE THREAD

**Issue by Windvis** [matteobruni/tsparticles#515]
**Is your feature request related to a problem? Please describe.**
The current implementation requires you to add an id to a container or canvas, and pass that id when initialising tsparticles. Since most frameworks make it possible to get access to DOM references it would be nice if that was also supported. 

This would allow frameworks like Svelte or Ember to implement a wrapper as an [`action`](https://svelte.dev/docs#use_action) or [`modifier` ](https://github.com/ember-modifier/ember-modifier)respectively. (Other frameworks might have similar functionality.)

**Describe the solution you'd like**
Make it possible to initialise tsparticles like this:

```js
tsparticles.load(canvasOrContainerElement, options)
```
**Describe alternatives you've considered**
Keep the current id string only api

**Additional context**

Potential Svelte wrapper api:
```html
<div use:tsparticles={options}></div>
```

Potential Ember wrapper api:
```html
<canvas {{tsparticles this.options}}></canvas>
```

**Comment by matteobruni** [comment]
Hi @Windvis.
I'm currently working on a Svelte component but the feature you're requesting is missing only in the exposed object and can be easily added.
I need to do some tests but I think this can be released in version 1.16.3.

**Comment by matteobruni** [comment]
Now you can use `tsParticles.set(id, element, options)` to use an element, the `id` is just a string used only to retrieve the container.

**Comment by Windvis** [comment]
Thanks for working on this so fast but I'm not sure what the benefit is from using the new invocation over the other one? My intention was  to drop the id requirement altogether and use the element reference as the identifier instead. I think most modern frameworks have better ways to get references to dom elements, so passing the element in directly seems like a cleaner solution than having tsparticles query the dom for it.

**Comment by matteobruni** [comment]
The `id` is not linked by the Dom with the `set` method, is used by tsParticles internally to retrieve same containers and avoid duplicates by destroying the old and create a new one.
In the `load` method the `id` is used to retrieve the DOM element and it's set to the particles container too.
