### ISSUE TITLE
[Docs] Restructure the readme

### ISSUE THREAD

**Issue by Windvis** [matteobruni/tsparticles#516]
I think the current version of the readme is overloaded with info which is a bit overwhelming (at least for me).

Personally I would:
- move the vanilla js usage instructions to the top. I first thought it wasn't documented since it's so far to the bottom at the moment. The jQuery code is also the first thing you see.
- remove the documentation of all the wrapper / component projects and just link to their respective readmes instead
- move the demos to a separate file and link to it
- remove the stargazers graph I'm not sure why it's needed in the readme :smile: 
- remove one of the two "import and require" sections. They seem to be duplicates.
- move the options documentation to the readme instead of a separate file

**Comment by matteobruni** [comment]
Thanks, the README in `dev` branch was already under rework but thanks for the tips!
