### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by BonnY0** [matteobruni/tsparticles#5341]
### What happened?

There is sort of a memory leak, the number of particles increases and memory usage spikes, when I zoom out in browser or use desktop mode when testing on mobile phone. How do I keep the same number of particles on any screen size.

The first picture shows normal browser zoom at 100% and the second shows zoomed out you can see that the number of particles is a lot more than it is supposed to be.
![100%z](https://github.com/tsparticles/tsparticles/assets/65781644/b28675c6-d8f8-4526-8cdf-b21f56fe6688)
![zoomout](https://github.com/tsparticles/tsparticles/assets/65781644/97aa1389-13e5-491d-abac-99290ec01ff0)

### tsParticles Version

3.0.2

### tsParticles Configuration

```json
tsParticles.load({ 
  id: "tsparticles", 
  options: { 
    preset: "links",
    background: {
      color: {
        value: "#00000" 
      }
    },
    fullScreen: {
      enable: false 
    },
    particles: {
      number: {
        value: 150,
        density: {
          enable: true,
          value_area: 400 
        }
      },
      links: {
        color: "#0d044f" 
      }
    }
  } 
});
```

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
Disable density in particles number options

**Comment by Bakir0-dev** [comment]
Yes but now in mobile version the number of particles is a lot in default resolution

**Comment by matteobruni** [comment]
You asked same number in any screen size, that’s how you achieve it. If you want different numbers between mobile and desktop, use two different options and load them checking the browser name or other parameters

**Comment by Bakir0-dev** [comment]
How do I achieve that, is it possible with config parameters or I need another js checking for browser size

**Comment by matteobruni** [comment]
> How do I achieve that, is it possible with config parameters or I need another js checking for browser size

For mobile detection you need custom js code, responsive options are based on screen size

**Comment by Bakir0-dev** [comment]
Thanks
