### ISSUE TITLE
Particles Trails rework

### ISSUE THREAD

**Issue by matteobruni** [matteobruni/tsparticles#608]
Actually trail is made by covering the canvas by a semi-transparent rectangle, its transparency is something like 100/value but the result can be a dotted trail instead of a continuous line.

A drawn trail could give a better result, but we should consider performance too. The length is how many position should be kept to draw a multi-point line (or multiple lines).

Cover color will become obsolete if this way is taken

**Comment by aaronleopold** [comment]
Hey there, I can try and look into this. I'm new to the repository though, would you be able to give me some pointers or a general idea of where / what pieces of source code to read through currently for this?

**Comment by matteobruni** [comment]
Hi @aaronleopold,

This issue is kinda complicated because it needs a rework of the actual trail implementation.

Actually the trail is created in `CanvasUtils` with a rectangle filling the canvas with color transparency that creates all trails.

This behavior can be kept, but a particle drawn trail could bring a visually better effect. The particle is drawn in `CanvasUtils` too.

I don't have any indication of how this should be implemented, I didn't think anything on this issue for now, but what I'd expect is a trail made without breaking actual performance.

The options to customize the trails are in the `particles.move.trail` options.
