### ISSUE TITLE
Refactor var names in CamelCase

### ISSUE THREAD

**Issue by matteobruni** [matteobruni/tsparticles#61]
Referencing issue https://github.com/VincentGarreau/particles.js/issues/414 from old project

> Need to refactor some var names and function to make happy codacy

@thomas-demagny are we ok here?

**Comment by abhishekcrdsa7** [comment]
Can I work on this? As far as I understand, I just need to refractor the variable names and accordingly make changes where ever that variable is being used?

**Comment by matteobruni** [comment]
Yeah sure, for now don't refactor IOptions, I don't want to break the old configs for now. If you find some variable names that can be refactored totally don't hesitate.

**Comment by matteobruni** [comment]
You can create a pull request to `dev` branch with the changes

**Comment by abhishekcrdsa7** [comment]
Sure @matteobruni
