### ISSUE TITLE
Not able to import a local svg to the polygon mask.

### ISSUE THREAD

**Issue by saiashish90** [matteobruni/tsparticles#619]
polygon       : {
					data              : {
						path   : './smalldeer.svg',
						width  : '1',
						height : '1'
					},
					draw              : {
						enable    : true,
						lineColor : 'rgba(255,255,255,0.2)',
						lineWidth : 0.3
					},
					move              : {
						radius : 10
					},
					inlineArrangement : 'equidistant',
					scale             : 0.5,
					type              : 'inline'
				}

this is my config for the polygon. i just particles that arent in the shape of the svg

**Comment by matteobruni** [comment]
Hello @saiashish90 

For loading an external file you must use the `url` property in the `polygon` object. `data` is used for loading SVG strings without using the file

You can see it here: https://github.com/matteobruni/tsparticles/wiki/tsParticles-Options-Polygon-Mask

Or this sample: https://codepen.io/matteobruni/pen/yLNpgKW
