### ISSUE TITLE
Canvas width and height drastic increase on mobile devices

### ISSUE THREAD

**Issue by devdominus** [matteobruni/tsparticles#640]
On desktop the canvas width and height is the screen's width and height. But, on opening it on any mobile device or responsive view using console, the canvas width and height becomes more than double.

It is implemented at devdominus.in

**Comment by matteobruni** [comment]
Hi @devdominus,

I tried your website on my mobile device but the canvas is ok, I tried switching views too but nothing happened.

Can you share some code to reproduce the issue?

If you are reading canvas size in JavaScript those values can be multiplied by the device pixel ratio if `detectRetina` (or `retina_detect`) is set to `true`.

Setting that property to `false` uses a device pixel ratio of `1` on every device but on retina devices the particles and their links will be a little blurred because the canvas is stretched.

**Comment by devdominus** [comment]
![expected](https://user-images.githubusercontent.com/68273556/88915414-d981d480-d281-11ea-85dd-51cbbaf7481f.png)
This is how I expect it to be.
![result](https://user-images.githubusercontent.com/68273556/88917481-72feb580-d285-11ea-877c-a8e2f11064f8.png)
But if I open it on my phone it shows like this.
On PC to reproduce, view in mobile responsive, go to another page and come back to home.

This is how I've used it.

function Home() {

    return (
      <div className="page">
        
        <Particles className="background"
            params={{
              "particles": {
                "number": {
                  "value": 60,
                  "density": {
                    "enable": true,
                    "value_area": 650
                  }
                },
                "color": {
                  "value": "#ff8f00"
                },
                "shape": {
                  "type": "circle",
                  "stroke": {
                    "width": 0,
                    "color": "#000000"
                  },
                  "polygon": {
                    "nb_sides": 8
                  },
                },
                "opacity": {
                  "value": 1,
                  "random": false,
                  "anim": {
                    "enable": false,
                    "speed": 1,
                    "opacity_min": 0.1,
                    "sync": false
                  }
                },
                "size": {
                  "value": 3,
                  "random": true,
                  "anim": {
                    "enable": false,
                    "speed": 40,
                    "size_min": 0.1,
                    "sync": false
                  }
                },
                "line_linked": {
                  "enable": true,
                  "distance": 160,
                  "color": "#ff8f00",
                  "opacity": 0.69,
                  "width": 0.80,
                },
                "move": {
                  "enable": true,
                  "speed": 2,
                  "direction": "top-right",
                  "random": false,
                  "straight": false,
                  "out_mode": "out",
                  "bounce": false,
                  "attract": {
                    "enable": false,
                    "rotateX": 1200,
                    "rotateY": 1200
                  }
                }
              },
              "interactivity": {
                "detect_on": "canvas",
                "events": {
                  "onhover": {
                    "enable": false,
                    "mode": "bubble"
                  },
                  "onclick": {
                    "enable": true,
                    "mode": "repulse"
                  },
                  "resize": true
                },
                "modes": {
                  "grab": {
                    "distance": 400,
                    "line_linked": {
                      "opacity": 1
                    }
                  },
                  "bubble": {
                    "distance": 400,
                    "size": 40,
                    "duration": 2,
                    "opacity": 8,
                    "speed": 3
                  },
                  "repulse": {
                    "distance": 100,
                    "duration": 0.4
                  },
                  "push": {
                    "particles_nb": 4
                  },
                  "remove": {
                    "particles_nb": 2
                  }
                }
              },
              
            }}/>
            <div className="home-parent">
            <div className="span-middle">
            <img src={Logo} className="logo" alt=""/>
            
            <h1 className="home-header">Dev Dominus</h1>
            <h3 className="home-subtext">Digital Solutions</h3>
            
            </div>
            </div>
        
        </div>
    )
}

This is the css for the background class

.background{
  position: absolute !important;
    width: 100vw;
    height: 90vh;
    z-index:-1
    }

**Comment by devdominus** [comment]
Thank You!. Setting retina_detect:false fixed the issue on my phone. But does that mean it will get stretched in retina devices?
![result](https://user-images.githubusercontent.com/68273556/88918869-d8ec3c80-d287-11ea-8f6a-71c4e64cdd99.png)
This was how it was when retina_detect was true

**Comment by matteobruni** [comment]
Particles and links will be a little blurry on retina devices. But this could also be unnoticeable.

Which version are you using?

**Comment by devdominus** [comment]
I'm using it via react-particle-js so I'm not sure

**Comment by matteobruni** [comment]
Which version of that library?

**Comment by devdominus** [comment]
3.3.0
