### ISSUE TITLE
Help, can't find documentation for making particles be contained to 1 div ://

### ISSUE THREAD

**Issue by ShadiestGoat** [matteobruni/tsparticles#737]
Just as the title says. I need to keep particles contained to 1 div, and I know its possible due to a pull request made (and approved) by someone, I just don't really get how to do it. 
Oh, and in case it is needed, I need to contain to a div to be able to make a parallax footer

**Comment by matteobruni** [comment]
Hi @ShadiestGoat,

I don't understand what do you want to achieve, particles are already contained in a single div. You can set it to act like a background using `position: fixed` or `position: absolute` and a 100% height and width or use it like any other div of your website.

This is a normal div with particles: https://codepen.io/matteobruni/pen/XWbBxEm

If you want to have one or more div have some interaction with the particles you can set the `interactivity.onDiv` properties like this sample: https://codepen.io/matteobruni/pen/NWxWXQB or https://codepen.io/matteobruni/pen/mdVdPKj

**Comment by ShadiestGoat** [comment]
heya @matteobruni, thanks for your reply!

I do want to set it as a background, but only to a specific div, and for me to be able to put elements behind it. The way that you show in the pen should work, however I am having trouble understanding why it doesnt work on my project :/
I have a footer that is supposed to be revealed only if scrolled down to the bottom. It has a z-index of -1, and the <body> tag has a margin-bottom of 9% to be able to show this. It usually does show it, however if I turn on the particles, it stops working, and the particles just show over it
![image](https://user-images.githubusercontent.com/48590492/90930051-c500aa00-e3f1-11ea-83cc-696cf27ba875.png)
![image](https://user-images.githubusercontent.com/48590492/90930226-1d37ac00-e3f2-11ea-896f-fd292d8711c0.png)

**Comment by ShadiestGoat** [comment]
(this is an example of the footer: https://codepen.io/tamedia/full/ByPyBP)

**Comment by matteobruni** [comment]
Have you tried setting `position: relative` to the div that needs particles background and `position: absolute` to the particles div (that needs to be inside the first div)?

**Comment by ShadiestGoat** [comment]
Holy shiittt ;-;
Thank you so much! I have been trying to do this for the past several days, and couldnt figure it out, nor find it anywhere so thank you so much ^^
