### ISSUE TITLE
PolygonMask issues on mobile devices

### ISSUE THREAD

**Issue by matteobruni** [matteobruni/tsparticles#84]
Polygon Mask in mobile devices, probably all retina enabled devices, has some issues.
The existing sample https://particles.matteobruni.it/#mask will display correctly on desktop browser, on my mobile device it's showing the particles and the mask in top-left corner.

**Comment by hoonsubin** [comment]
I'm still having this issue on my retina enabled mobile devices (Mac seems to work fine for some reason).
I was testing it out with the react typescript tsparticles template on version `1.18.2`. Are the modified milestones implying that this error will be fixed on `1.9.0` version?

Here are some screenshots

<img width="1781" alt="Screen Shot 2020-10-08 at 12 56 15 PM" src="https://user-images.githubusercontent.com/40356749/95413229-d7b14d00-0965-11eb-87ae-99ea1b205148.png">
<img height="600" alt="IMG_0600" src="https://user-images.githubusercontent.com/40356749/95413116-93be4800-0965-11eb-9c28-2ec27b5e3504.png">

**Comment by matteobruni** [comment]
It looks like a bug the error you are receiving, I’ll have a look as soon as possible
